on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run the local file
        uses: ./
        with:
          organization: vj-abigo
          label: invite me
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
